---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jmix-lab
  namespace: flux-system
spec:
  interval: 60s
  path: ./infra/dev/kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: jmix-lab
  targetNamespace: default
  timeout: 3m0s
  wait: true
