---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: jmix-lab
  namespace: flux-system
spec:
  interval: 1m0s
  secretRef:
    name: github-repo-cred
  ref:
    branch: main
  url: https://github.com/dgodlevskiy/jmix-lab
