apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmix-lab-deployment
  labels:
    app: jmix-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jmix-lab
  template:
    metadata:
      labels:
        app: jmix-lab
    spec:
      containers:
      - name: jmix-lab
        image: warhammster.jfrog.io/wh-docker/jmix-lab
        ports:
        - containerPort: 8080
        env:
        - name: CRM_DB_HOST
          value: 10.96.59.33:30432
        - name: CRM_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-root-username
        - name: CRM_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-root-password
      imagePullSecrets:
        - name: regcred
