name: Promote tag to qa

on: workflow_dispatch

jobs:
  promote-qa:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Define image tag
        id: tags
        run: |
          SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          
          TAG="qa-$SHORT_SHA-${{ github.run_number }}"
          echo "Tag: $TAG"

          git tag --points-at ${{ github.sha }} -l dev-*

          TAG_SOURCE=$(git tag --points-at ${{ github.sha }} -l dev-*)
          echo "Source tag: $TAG_SOURCE"
          
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Add git tag with image tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ steps.tags.outputs.tag }}
          git push origin ${{ steps.tags.outputs.tag }}
  
  # promote-stage:
  #   runs-on: ubuntu-latest
  #   environment: stage
  #   needs: promote-qa
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Pull from QA registery
  #       run: echo 'Pull from QA registery'

  #     - name: Push to Stage
  #       run: echo 'Pushing to Stage registery with new tag'
  
  # promote-prod:
  #   runs-on: ubuntu-latest
  #   environment: prod
  #   needs: promote-stage
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Pull from Stage registery
  #       run: echo 'Pull from Stage registery'

  #     - name: Push to Prod
  #       run: echo 'Pushing to prod registery with new tag'
